/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jresendiz' at '4/29/16 12:13 PM' with Gradle 2.12
 *
 * @author jresendiz, @date 4/29/16 12:13 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
